import { randomBytes, randomUUID } from "node:crypto";
import { lstat, mkdir, realpath, rename, stat } from "node:fs/promises";
import path from "node:path";

import { sqlite } from "../db/index.js";
import { resolveWorkspacePath } from "../lib/workspace.js";
import { logger } from "../lib/logger.js";
import {
  ARTIFACT_SELECT_COLUMNS,
  ConversationArtifactError,
  type ConversationArtifactRecord,
} from "./conversation-artifacts.js";
import { withArtifactPathLock } from "./artifact-path-lock.js";
import { recordFileLifecycleEvent } from "./file-lifecycle-audit.js";

/**
 * User-initiated artifact deletion. Implements the two-step
 * prepare/confirm flow, the 30-day hidden trash window, and the path-version
 * tombstone rule from
 * `docs/portal-file-retention-and-library-governance-work-package.md` §8.
 *
 * Safety invariants enforced here, not in the Portal:
 *  - The browser never submits userId / instanceId / relativePath / trash path.
 *    Scope comes from the authenticated connector session.
 *  - Only `durable_library` + `visibility=library` rows are deletable.
 *  - The confirmation token is bound to user+instance+artifact+path+checksum,
 *    single-use, short-lived.
 *  - The file is moved (never `unlink`ed) into an opaque `.trash/artifacts/`
 *    subdir; the trash path is generated by the server, never the client.
 *  - All same-path versions are tombstoned together so an older version cannot
 *    re-surface after deletion.
 */

const DAY_MS = 24 * 60 * 60 * 1000;
/** Hidden recovery window before the trash is physically purged. */
export const ARTIFACT_TRASH_RETENTION_MS = 30 * DAY_MS;
/** Confirmation token lifetime. */
const DELETE_TOKEN_TTL_MS = 10 * 60 * 1000;
const TRASH_ROOT = ".trash/artifacts";

const pendingDeleteTokens = new Map<string, PendingDeleteToken>();
let failNextMoveForTest = false;

interface PendingDeleteToken {
  tokenId: string;
  artifactId: string;
  userId: string;
  instanceId: string;
  relativePath: string;
  checksum: string | null;
  issuedAt: string;
  expiresAt: string;
  status: "prepared" | "moving" | "failed" | "completed" | "expired";
  trashRelativePath: string | null;
  purgeAt: string | null;
  deletedVersions: number | null;
}

export interface ArtifactDeletePrepareResult {
  tokenId: string;
  artifactId: string;
  title: string;
  fileName: string;
  displayPath: string;
  sizeBytes: number;
  category: string;
  expiresAt: string;
  impactNotes: string[];
}

/**
 * Step 1 of the delete flow. Validates that the artifact is deletable under
 * the caller's scope and returns a single-use confirmation token plus the
 * human-facing impact notes the Portal must show in its confirm dialog.
 */
export async function prepareArtifactDeletion(input: {
  artifactId: string;
  userId: string;
  instanceId: string;
}): Promise<ArtifactDeletePrepareResult> {
  const record = requireArtifactRecord(input.artifactId, input.userId, input.instanceId);
  assertDeletable(record);
  const now = new Date();
  const tokenId = `del_${randomUUID()}`;
  const token: PendingDeleteToken = {
    tokenId,
    artifactId: record.artifactId,
    userId: input.userId,
    instanceId: input.instanceId,
    relativePath: record.relativePath,
    checksum: record.checksum ?? null,
    issuedAt: now.toISOString(),
    expiresAt: new Date(now.getTime() + DELETE_TOKEN_TTL_MS).toISOString(),
    status: "prepared",
    trashRelativePath: null,
    purgeAt: null,
    deletedVersions: null,
  };
  pendingDeleteTokens.set(tokenId, token);
  sqlite.prepare(
    `INSERT INTO artifact_delete_confirmations (
       token_id, artifact_id, user_id, instance_id, relative_path, checksum,
       issued_at, expires_at, status, updated_at
     ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'prepared', ?)`,
  ).run(
    token.tokenId,
    token.artifactId,
    token.userId,
    token.instanceId,
    token.relativePath,
    token.checksum,
    token.issuedAt,
    token.expiresAt,
    token.issuedAt,
  );
  const displayPath = record.relativePath.replace(/^reports\//, "");
  return {
    tokenId,
    artifactId: record.artifactId,
    title: record.title,
    fileName: record.fileName,
    displayPath,
    sizeBytes: record.sizeBytes,
    category: categoryForImpactNotes(record.relativePath),
    expiresAt: token.expiresAt,
    impactNotes: buildImpactNotes(record.relativePath),
  };
}

export interface ArtifactDeleteConfirmResult {
  artifactId: string;
  deletedVersions: number;
  trashRelativePath: string;
  purgeAt: string;
}

/**
 * Step 2 of the delete flow. Consumes the token, moves the underlying file
 * into the hidden trash area, tombstones every same-path version, and returns
 * the recovery metadata. Repeated confirm calls with the same token return the
 * original outcome idempotently instead of moving the file again.
 */
export async function confirmArtifactDeletion(input: {
  tokenId: string;
  userId: string;
  instanceId: string;
}): Promise<ArtifactDeleteConfirmResult> {
  const token = pendingDeleteTokens.get(input.tokenId) ?? readDeleteConfirmation(input.tokenId);
  if (!token) {
    throw new ConversationArtifactError("ARTIFACT_DELETE_CONFIRMATION_EXPIRED", input.tokenId);
  }
  if (token.userId !== input.userId || token.instanceId !== input.instanceId) {
    throw new ConversationArtifactError("ARTIFACT_SCOPE_MISMATCH", input.tokenId);
  }
  if (token.status === "expired") {
    throw new ConversationArtifactError("ARTIFACT_DELETE_CONFIRMATION_EXPIRED", input.tokenId);
  }
  if (token.status === "completed") return completedResult(token);
  if (Date.now() > Date.parse(token.expiresAt) && token.status === "prepared") {
    pendingDeleteTokens.delete(input.tokenId);
    sqlite.prepare(`UPDATE artifact_delete_confirmations SET status = 'expired', updated_at = ? WHERE token_id = ?`).run(new Date().toISOString(), input.tokenId);
    throw new ConversationArtifactError("ARTIFACT_DELETE_CONFIRMATION_EXPIRED", input.tokenId);
  }
  return withArtifactPathLock(input.userId, token.relativePath, async () => {
    const current = readDeleteConfirmation(input.tokenId);
    if (!current) throw new ConversationArtifactError("ARTIFACT_DELETE_CONFIRMATION_EXPIRED", input.tokenId);
    if (current.status === "completed") return completedResult(current);

    const now = new Date();
    const trashRelativePath = current.trashRelativePath ?? path.posix.join(
      TRASH_ROOT,
      randomBytes(12).toString("hex"),
      path.basename(current.relativePath),
    );
    const purgeAt = current.purgeAt ?? new Date(now.getTime() + ARTIFACT_TRASH_RETENTION_MS).toISOString();
    let deletedVersions = current.deletedVersions ?? 0;

    if (current.status === "prepared") {
      const record = requireArtifactRecord(current.artifactId, input.userId, input.instanceId);
      if (record.relativePath !== current.relativePath || (record.checksum ?? null) !== current.checksum) {
        throw new ConversationArtifactError("ARTIFACT_DELETE_CONFLICT", "artifact changed between prepare and confirm");
      }
      assertDeletable(record);
      const tombstoneAndPersist = sqlite.transaction(() => {
        deletedVersions = tombstoneArtifactPath({
          userId: input.userId,
          instanceId: input.instanceId,
          relativePath: current.relativePath,
          trashRelativePath,
          purgeAt,
          deletedBy: input.userId,
          now,
        });
        sqlite.prepare(
          `UPDATE artifact_delete_confirmations
           SET status = 'moving', trash_relative_path = ?, purge_at = ?,
               deleted_versions = ?, error_code = NULL, updated_at = ?
           WHERE token_id = ?`,
        ).run(trashRelativePath, purgeAt, deletedVersions, now.toISOString(), input.tokenId);
      });
      tombstoneAndPersist();
    }

    try {
      await moveArtifactToTrash({
        userId: input.userId,
        sourceRelativePath: current.relativePath,
        trashRelativePath,
      });
    } catch (error) {
      sqlite.prepare(
        `UPDATE artifact_delete_confirmations SET status = 'failed', error_code = ?, updated_at = ? WHERE token_id = ?`,
      ).run("ARTIFACT_DELETE_CONFLICT", new Date().toISOString(), input.tokenId);
      recordFileLifecycleEvent({
        entityType: "artifact",
        entityId: current.artifactId,
        userId: input.userId,
        instanceId: input.instanceId,
        event: "artifact.delete",
        status: "failure",
        reason: "move_failed",
        summary: { deletedVersions, purgeAt },
      });
      throw new ConversationArtifactError("ARTIFACT_DELETE_CONFLICT", (error as Error).message);
    }

    const completedAt = new Date().toISOString();
    sqlite.prepare(
      `UPDATE artifact_delete_confirmations
       SET status = 'completed', error_code = NULL, completed_at = ?, updated_at = ?
       WHERE token_id = ?`,
    ).run(completedAt, completedAt, input.tokenId);
    pendingDeleteTokens.delete(input.tokenId);
    recordFileLifecycleEvent({
      entityType: "artifact",
      entityId: current.artifactId,
      userId: input.userId,
      instanceId: input.instanceId,
      event: "artifact.delete",
      status: "success",
      summary: { deletedVersions, purgeAt },
    });
    return { artifactId: current.artifactId, deletedVersions, trashRelativePath, purgeAt };
  });
}

/**
 * Internal helper used by both the per-call confirm path and the trash-purge
 * job. Tombstones every visible version that shares the deleted path so an
 * older publish cannot resurface the file in the library list.
 */
export function tombstoneArtifactPath(input: {
  userId: string;
  instanceId: string;
  relativePath: string;
  trashRelativePath: string;
  purgeAt: string;
  deletedBy: string;
  now: Date;
}): number {
  const nowIso = input.now.toISOString();
  const result = sqlite
    .prepare(
      `UPDATE conversation_artifacts
       SET retention_class = 'trashed',
           visibility = 'hidden',
           deleted_at = ?,
           deleted_by = ?,
           delete_reason = 'user_deleted',
           trash_relative_path = ?,
           purge_at = ?,
           updated_at = ?
       WHERE user_id = ? AND instance_id = ? AND relative_path = ? AND deleted_at IS NULL`
    )
    .run(
      nowIso,
      input.deletedBy,
      input.trashRelativePath,
      input.purgeAt,
      nowIso,
      input.userId,
      input.instanceId,
      input.relativePath,
    );
  return result.changes;
}

async function moveArtifactToTrash(input: {
  userId: string;
  sourceRelativePath: string;
  trashRelativePath: string;
}): Promise<string> {
  if (failNextMoveForTest) {
    failNextMoveForTest = false;
    throw new Error("injected artifact move failure");
  }
  const workspacePath = resolveWorkspacePath(input.userId);
  const reportsRoot = path.join(workspacePath, "reports");
  const sourcePath = path.resolve(workspacePath, input.sourceRelativePath);
  let realReportsRoot: string;
  let realSource: string;
  const trashTargetPath = path.join(workspacePath, input.trashRelativePath);
  try {
    [realReportsRoot, realSource] = await Promise.all([realpath(reportsRoot), realpath(sourcePath)]);
  } catch {
    try {
      const existingTrash = await stat(trashTargetPath);
      if (existingTrash.isFile()) return input.trashRelativePath;
    } catch {
      // Continue to the deterministic conflict below.
    }
    throw new ConversationArtifactError("ARTIFACT_DELETE_CONFLICT", "source and trash bytes are both missing");
  }
  if (!isWithin(realReportsRoot, realSource)) {
    throw new ConversationArtifactError("ARTIFACT_INVALID_PATH", input.sourceRelativePath);
  }
  const sourceStat = await lstat(realSource);
  if (sourceStat.isSymbolicLink() || !sourceStat.isFile()) {
    throw new ConversationArtifactError("ARTIFACT_NOT_DELETABLE", "only regular files can be trashed");
  }
  await mkdir(path.dirname(trashTargetPath), { recursive: true });
  // `rename` is atomic on the same filesystem; fall back to copy+rm only if
  // the trash area somehow lives on a different mount (it never should, since
  // it is inside the same workspace).
  try {
    await rename(realSource, trashTargetPath);
  } catch (error) {
    logger.warn(`artifact trash rename failed, falling back to copy userId=${input.userId} relativePath=${input.sourceRelativePath}: ${(error as Error).message}`);
    const { copyFile, rm } = await import("node:fs/promises");
    await copyFile(realSource, trashTargetPath);
    await rm(realSource, { force: true });
  }
  return input.trashRelativePath;
}

/**
 * Trash purge job. Removes files whose `purge_at` has passed and that were
 * moved into the trash by this service (only `.trash/artifacts/...` paths are
 * eligible). Idempotent: a missing file is treated as success.
 */
export async function purgeExpiredArtifactTrash(input: {
  now?: Date;
  dryRun?: boolean;
  limit?: number;
}): Promise<{ scanned: number; purgedFiles: number; purgedBytes: number; missing: number; errors: number }> {
  const now = input.now ?? new Date();
  const nowIso = now.toISOString();
  const limit = Math.min(Math.max(input.limit ?? 200, 1), 200);
  const rows = sqlite
    .prepare(
      `SELECT
         artifact_id AS artifactId,
         user_id AS userId,
         instance_id AS instanceId,
         trash_relative_path AS trashRelativePath,
         size_bytes AS sizeBytes
       FROM conversation_artifacts
       WHERE retention_class = 'trashed'
         AND purge_at IS NOT NULL
         AND purge_at <= ?
         AND trash_relative_path IS NOT NULL
       ORDER BY purge_at ASC
       LIMIT ?`
    )
    .all(nowIso, limit) as Array<{
      artifactId: string;
      userId: string;
      instanceId: string;
      trashRelativePath: string;
      sizeBytes: number;
    }>;
  const summary = { scanned: rows.length, purgedFiles: 0, purgedBytes: 0, missing: 0, errors: 0 };
  for (const row of rows) {
    if (!isSafeTrashRelativePath(row.trashRelativePath)) {
      summary.errors += 1;
      logger.warn(`artifact trash purge refused unsafe path userId=${row.userId} trashRelativePath=${row.trashRelativePath}`);
      if (!input.dryRun) recordPurgeAudit(row, "failure", "unsafe_trash_path");
      continue;
    }
    const workspacePath = resolveWorkspacePath(row.userId);
    const trashRoot = path.join(workspacePath, TRASH_ROOT);
    const targetPath = path.resolve(workspacePath, row.trashRelativePath);
    let realTrashRoot: string;
    let realTarget: string;
    try {
      [realTrashRoot, realTarget] = await Promise.all([realpath(trashRoot), realpath(targetPath)]);
    } catch {
      summary.missing += 1;
      markTrashPurged(row.artifactId);
      if (!input.dryRun) recordPurgeAudit(row, "success", "already_missing");
      continue;
    }
    if (!isWithin(realTrashRoot, realTarget)) {
      summary.errors += 1;
      if (!input.dryRun) recordPurgeAudit(row, "failure", "trash_path_escape");
      continue;
    }
    let fileStat;
    try {
      fileStat = await stat(realTarget);
    } catch {
      summary.missing += 1;
      markTrashPurged(row.artifactId);
      if (!input.dryRun) recordPurgeAudit(row, "success", "already_missing");
      continue;
    }
    if (!fileStat.isFile() || fileStat.isSymbolicLink()) {
      summary.errors += 1;
      if (!input.dryRun) recordPurgeAudit(row, "failure", "not_regular_file");
      continue;
    }
    if (input.dryRun) {
      summary.purgedFiles += 1;
      summary.purgedBytes += row.sizeBytes;
      continue;
    }
    try {
      const { rm } = await import("node:fs/promises");
      await rm(realTarget, { force: true });
      summary.purgedFiles += 1;
      summary.purgedBytes += row.sizeBytes;
      markTrashPurged(row.artifactId);
      recordPurgeAudit(row, "success", "purged");
    } catch (error) {
      summary.errors += 1;
      logger.warn(`artifact trash purge failed userId=${row.userId} artifactId=${row.artifactId}: ${(error as Error).message}`);
      recordPurgeAudit(row, "failure", "unlink_failed");
    }
  }
  return summary;
}

function markTrashPurged(artifactId: string) {
  const now = new Date().toISOString();
  sqlite
    .prepare(
      `UPDATE conversation_artifacts
       SET delete_reason = COALESCE(delete_reason, 'user_deleted'),
           updated_at = ?
       WHERE artifact_id = ?`
    )
    .run(now, artifactId);
}

function recordPurgeAudit(
  row: { artifactId: string; userId: string; instanceId: string; sizeBytes: number },
  status: "success" | "failure",
  reason: string,
): void {
  recordFileLifecycleEvent({
    entityType: "artifact",
    entityId: row.artifactId,
    userId: row.userId,
    instanceId: row.instanceId,
    event: "artifact.purge",
    status,
    reason,
    summary: { sizeBytes: row.sizeBytes },
  });
}

function isSafeTrashRelativePath(relativePath: string): boolean {
  const normalized = relativePath.replace(/^\/+/, "");
  if (!normalized.startsWith(`${TRASH_ROOT}/`)) return false;
  const segments = normalized.split("/");
  return segments.every((segment) => segment && segment !== "." && segment !== "..");
}

function requireArtifactRecord(artifactId: string, userId: string, instanceId: string): ConversationArtifactRecord {
  const row = sqlite
    .prepare(
      `SELECT ${ARTIFACT_SELECT_COLUMNS}
       FROM conversation_artifacts
       WHERE artifact_id = ?`
    )
    .get(artifactId) as ConversationArtifactRecord | undefined;
  if (!row) throw new ConversationArtifactError("ARTIFACT_NOT_FOUND", artifactId);
  if (row.userId !== userId || row.instanceId !== instanceId) {
    throw new ConversationArtifactError("ARTIFACT_SCOPE_MISMATCH", artifactId);
  }
  return row;
}

function readDeleteConfirmation(tokenId: string): PendingDeleteToken | undefined {
  return sqlite.prepare(
    `SELECT token_id AS tokenId, artifact_id AS artifactId, user_id AS userId,
            instance_id AS instanceId, relative_path AS relativePath, checksum,
            issued_at AS issuedAt, expires_at AS expiresAt, status,
            trash_relative_path AS trashRelativePath, purge_at AS purgeAt,
            deleted_versions AS deletedVersions
     FROM artifact_delete_confirmations WHERE token_id = ?`,
  ).get(tokenId) as PendingDeleteToken | undefined;
}

function completedResult(token: PendingDeleteToken): ArtifactDeleteConfirmResult {
  if (!token.trashRelativePath || !token.purgeAt || token.deletedVersions === null) {
    throw new ConversationArtifactError("ARTIFACT_DELETE_CONFLICT", "completed delete is missing persisted outcome");
  }
  return {
    artifactId: token.artifactId,
    deletedVersions: token.deletedVersions,
    trashRelativePath: token.trashRelativePath,
    purgeAt: token.purgeAt,
  };
}

function assertDeletable(record: ConversationArtifactRecord): void {
  if (record.deletedAt) {
    throw new ConversationArtifactError("ARTIFACT_DELETED", record.artifactId);
  }
  // Only formally promoted, library-visible, durable artifacts are deletable
  // from the file tree. Pre-backfill rows (NULL columns) are NOT deletable —
  // backfill must classify them first, otherwise the user could "delete"
  // something the system has not yet promoted to the durable library.
  if (record.retentionClass !== "durable_library") {
    throw new ConversationArtifactError("ARTIFACT_NOT_DELETABLE", `retention_class=${record.retentionClass ?? "null"}`);
  }
  if (record.visibility !== "library") {
    throw new ConversationArtifactError("ARTIFACT_NOT_DELETABLE", `visibility=${record.visibility ?? "null"}`);
  }
}

function buildImpactNotes(relativePath: string): string[] {
  const notes = [
    "文件将立即从文档库和已打开标签中移除。",
    "系统保留 30 天恢复窗口，之后永久清除。",
  ];
  const category = categoryForImpactNotes(relativePath);
  if (category === "weekly" || category === "monthly" || category === "daily") {
    notes.push("删除该复盘文件可能影响后续复盘的历史输入。");
  }
  return notes;
}

function categoryForImpactNotes(relativePath: string): string {
  const normalized = relativePath.replace(/^\/+/, "");
  if (normalized.startsWith("reports/daily/") || normalized === "reports/daily") return "daily";
  if (normalized.startsWith("reports/weekly/") || normalized === "reports/weekly") return "weekly";
  if (normalized.startsWith("reports/monthly/") || normalized === "reports/monthly") return "monthly";
  if (normalized.startsWith("reports/company/") || normalized === "reports/company") return "company";
  if (normalized.startsWith("reports/metrics/") || normalized === "reports/metrics") return "metrics";
  if (normalized.startsWith("reports/memory/") || normalized === "reports/memory") return "memory";
  return "other";
}

function isWithin(rootPath: string, targetPath: string) {
  const relative = path.relative(rootPath, targetPath);
  return relative !== "" && !relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative);
}

/** Test-only: clears pending tokens so tests do not leak across cases. */
export function clearPendingDeleteTokensForTest(): void {
  pendingDeleteTokens.clear();
  failNextMoveForTest = false;
  sqlite.prepare(`DELETE FROM artifact_delete_confirmations`).run();
}

/** Test-only fault injection for the filesystem/SQLite recovery boundary. */
export function failNextArtifactMoveForTest(): void {
  failNextMoveForTest = true;
}
