import type { PortalErrorCode } from "./envelope";

/**
 * Maps connector error codes to stable HTTP status codes. Every artifact /
 * attachment / delete API route shares this map so the browser sees
 * consistent statuses (e.g. expired → 410 Gone, scope mismatch → 403) and can
 * render the right card state without parsing error messages.
 *
 * Unknown codes default to 400 at the call site.
 */
export const PORTAL_ERROR_STATUS: Record<PortalErrorCode, number | undefined> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  CONNECTOR_CONFLICT: 409,
  CONNECTOR_OFFLINE: 503,
  ASSISTANT_NOT_FOUND: 404,
  CONVERSATION_NOT_FOUND: 404,
  INVALID_REQUEST: 400,
  TIMEOUT: 504,
  CONCURRENT_TASK_LIMIT: 429,
  ACP_FAILED: 502,
  INTERNAL_ERROR: 500,
  ARTIFACT_INVALID_PATH: 400,
  ARTIFACT_NOT_FOUND: 404,
  ARTIFACT_UNSUPPORTED: 415,
  ARTIFACT_TOO_LARGE: 413,
  ARTIFACT_UNSAFE: 422,
  ARTIFACT_SCOPE_MISMATCH: 403,
  ARTIFACT_INVALID_CURSOR: 400,
  REPORT_ASSET_INVALID_PATH: 400,
  REPORT_ASSET_NOT_FOUND: 404,
  REPORT_ASSET_UNSUPPORTED: 415,
  REPORT_ASSET_TOO_LARGE: 413,
  // Legacy connector errors only. Current attachment.get returns ok:true with
  // a status descriptor for normal expired/deleted lifecycle states.
  ATTACHMENT_NOT_FOUND: 404,
  ATTACHMENT_EXPIRED: 410,
  ATTACHMENT_DELETED: 410,
  // Artifact lifecycle: expired / deleted are 410; not-deletable is a 405
  // (the resource exists but the method isn't allowed for its retention class).
  ARTIFACT_EXPIRED: 410,
  ARTIFACT_DELETED: 410,
  ARTIFACT_NOT_DELETABLE: 405,
  // Delete confirmation: required/expired/conflict are all 409-style client
  // state problems. We use 409 for conflict and 400 for the missing/expired
  // token so the modal can route to "re-prepare" vs "cancel".
  ARTIFACT_DELETE_CONFIRMATION_REQUIRED: 400,
  ARTIFACT_DELETE_CONFIRMATION_EXPIRED: 400,
  ARTIFACT_DELETE_CONFLICT: 409,
  WORKSPACE_FILE_INVALID_PATH: 400,
  WORKSPACE_FILE_NOT_FOUND: 404,
  WORKSPACE_FILE_FORBIDDEN: 403,
  WORKSPACE_FILE_TOO_LARGE: 413,
  WORKSPACE_FILE_LIMIT_EXCEEDED: 413,
  AUTOMATION_INVALID_SCOPE: 400,
  AUTOMATION_SCOPE_MISMATCH: 403,
  AUTOMATION_TASK_NOT_FOUND: 404,
  AUTOMATION_TASK_EXISTS: 409,
  AUTOMATION_REVISION_NOT_FOUND: 404,
  AUTOMATION_REVISION_CONFLICT: 409,
  AUTOMATION_INVALID_TASK_ID: 400,
  AUTOMATION_INVALID_NAME: 400,
  AUTOMATION_INVALID_DESCRIPTION: 400,
  AUTOMATION_INVALID_SCHEDULE: 400,
  AUTOMATION_ASSET_REQUIRED: 400,
  AUTOMATION_ASSET_INVALID_PATH: 400,
  AUTOMATION_ASSET_UNSUPPORTED_TYPE: 415,
  AUTOMATION_ASSET_TOO_LARGE: 413,
  AUTOMATION_ASSET_MIME_MISMATCH: 400,
  AUTOMATION_ASSET_INVALID_CONTENT: 422,
  AUTOMATION_ASSET_EXISTS: 409,
  AUTOMATION_ASSET_SOURCE_IMMUTABLE: 409,
  AUTOMATION_ASSET_NOT_FOUND: 404,
  AUTOMATION_ASSET_UNSAFE: 403,
  AUTOMATION_ASSET_CHECKSUM_MISMATCH: 422,
  AUTOMATION_WORKSPACE_NOT_FOUND: 404,
  AUTOMATION_RUN_NOT_FOUND: 404,
  AUTOMATION_RUN_IDEMPOTENCY_CONFLICT: 409,
  AUTOMATION_RUN_ALREADY_FINISHED: 409,
  AUTOMATION_RUN_STATUS_INVALID: 400,
  AUTOMATION_RUN_LEASE_LOST: 409,
  AUTOMATION_TASK_BUSY: 409,
  AUTOMATION_TASK_NOT_ACTIVE: 409,
  AUTOMATION_TASK_NEEDS_ATTENTION: 409,
  AUTOMATION_TASK_ARCHIVED: 409,
  AUTOMATION_BATCH_INVALID: 400,
  AUTOMATION_INVALID_CURSOR: 400,
  AUTOMATION_DATA_CORRUPT: 500,
  ASSET_INVALID_SCOPE: 400,
  ASSET_NOT_FOUND: 404,
  ASSET_SCOPE_MISMATCH: 403,
  ASSET_UNSUPPORTED_FORMAT: 415,
  ASSET_TOO_LARGE: 413,
  ASSET_MIME_MISMATCH: 400,
  ASSET_INVALID_CONTENT: 422,
  ASSET_ARCHIVED: 409,
  ASSET_VERSION_CONFLICT: 409,
  ASSET_IDEMPOTENCY_CONFLICT: 409,
  ASSET_COMMIT_FAILED: 500,
  ASSET_PATH_UNSAFE: 403,
  ASSET_CONFIRMATION_REQUIRED: 400,
  ASSET_FOLDER_NOT_FOUND: 404,
  ASSET_FOLDER_NAME_CONFLICT: 409,
  ASSET_FOLDER_DEPTH_EXCEEDED: 400,
  ASSET_FOLDER_NOT_EMPTY: 409,
  UPLOAD_REQUEST_TOO_LARGE: 413,
  USER_STORAGE_QUOTA_EXCEEDED: 409,
  REPORT_MAPPING_NOT_FOUND: 404
};

/**
 * Resolves a connector error code to an HTTP status, falling back to 400 for
 * forward-compatible unknown codes. Routes use this instead of indexing the
 * map directly so a future code never throws at runtime.
 */
export function statusForCode(code: string): number {
  return PORTAL_ERROR_STATUS[code as PortalErrorCode] ?? 400;
}
